SUDO_ID = {@Delta_Say,@sadroid,@Parhamppoker,@Ali_gs_m} --آیدی سودو های ربات (ربات cli , api  قرار بدید)
Full_Sudo = {@Delta_Say} -- آیدی سودو اصلی
TD_ID = Square_PantS_Robot -- آیدی ربات
Sudoid = @Delta_Say -- آیدی سودو اصلی
BotHelper = @Parhamppoker -- آیدی هلپر
UserBotHelper = 'Parhamppoker' -- یوزرنیم هلپر
LinkSuppoRt = 'https://t.me/joinchat/G3QlBVE2sC67CfhniEF1wQ' -- لینک گروه ساپورت
UserSudo = '@Dlta_Say' -- یوزرنیم سازنده
PvUserSudo = '@Erfwn_Pv_Bot' -- پیام رسان سازنده
Channel = '@Hackkade' -- یوزرنیم کانال 
ChannelInline = 'Hackkade' --یوزنیم کانال بدون @
token = '468680160:AAE_lWiN9LgNC48zKOsoVSjICjCB-Dg7O4k' -- توکن ربات api
